apiVersion: apps/v1
kind: Service
metada:
  name: image-convert-springboot-ser
  namespace: general
  annotations: 
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector: 
    app: image-converter-springboot
  type: LoadBalancer