apiVersion: kustomize.config.k8s.io/v1beta1
kind: kustomization

bases:
- ../base

images:
- name: IMAGE
  newName: gcr.io/myProject1/general/develop
  newTag: latest

configMapGenerator:
  - name: image-convert-springboot-cmg
    namespace: image-converter
    literals:
      - DB_URL=jdbc:postgresql://image-convert-db:5452/image-convert